"""common/pgdb/schema.py —— PostgreSQL 侧的完整 DDL。

OWNS:
    init_tables()          —— 幂等，可反复执行
    verify_schema()        —— 断言列集与列序，与 SQLite 新库逐列比对
    reset_all()            —— 测试/清库用（TRUNCATE ... RESTART IDENTITY）

--------------------------------------------------------------------------
类型决策（已定，不要推翻）
--------------------------------------------------------------------------
* 时间戳一律 ``text``，格式 ``'%Y-%m-%d %H:%M:%S'``，**不是** timestamptz。
  硬证据：server/app.py:1168 与 487 对该值做 ``datetime.strptime(x[:19], ...)``，
  datetime 对象不可下标 → TypeError；而且 asyncpg 会把 timestamptz 还成
  datetime，FastAPI 再序列化成 ISO-8601，erpAPI 拿到的每一条 created_at/
  updated_at 都变形。
  ⚠ ``DEFAULT CURRENT_TIMESTAMP`` 在 PG 的 text 列上**不会报错**，但会存成
  ``'2026-08-04 20:25:57.851686+00'``（带微秒和时区偏移）——静默变形。
  所以默认值一律写 ``to_char(clock_timestamp() AT TIME ZONE 'UTC', ...)``。
  用 clock_timestamp() 而不是 now()：SQLite 的 CURRENT_TIMESTAMP 在同一个事务里
  会往前走，now() 冻在事务开始时刻。
* 布尔一律 ``integer`` 0/1，**不是** boolean。
  ``/api/batches`` 的 needs_screenshot 在基线里是 int ``0``，而
  ``/api/tasks/pull`` 的同名字段是 ``false``（因为 database.py:1222 显式
  ``bool()`` 了一次）。同一个逻辑布尔在 API 上有两种形状，两种都被钉死了。
* id 一律 ``bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY``。
  实测：identity + ON CONFLICT DO NOTHING 与 SQLite AUTOINCREMENT + INSERT OR
  IGNORE **烧号方式完全一致**（插 a,b,c 再插 a,b,c 再插 d,e → 1,2,3,7,8）。
  基线钉死了这些空洞：golden_batch_b 的 id 是 3 不是 2，task id 是 1,3,7,8。
  → 绝不允许"先 SELECT 再 INSERT" / "WHERE NOT EXISTS" 之类的预过滤优化。
  用 BY DEFAULT 而非 ALWAYS：ALWAYS 会挡住将来的显式 id 回填。
* 所有 text 列都带 ``COLLATE "C"``。
  SQLite 的 TEXT 比较是 BINARY（字节序）。scraper_dev 恰好是 C.UTF-8 所以现在
  看不出问题，但生产库若用 en_US.UTF-8 建，``iter_results`` 的 keyset 游标
  （``ba.asin > $n ORDER BY ba.asin``）会重排导出行序、``updated_at < cutoff``
  的回收判定也会漂。逐列 COLLATE "C" 能扛住"恢复到另一台 collation 不同的库"。

--------------------------------------------------------------------------
不移植的东西
--------------------------------------------------------------------------
* 13 条 PRAGMA、WAL、只读连接池 —— 见 pool.py / admin.py。
* database.py:609-717 的 27 条 ``ALTER TABLE ... except: pass`` 迁移阶梯 ——
  **不移植**。它在新库上全是死代码（列都已在 CREATE TABLE 里），而在 PG 里
  一旦落进事务，第一条失败就会让后续全部 ``InFailedSQLTransactionError``，
  再被裸 except 吞掉 → 半张表悄悄建不出来。这里直接一次性建全列。
  代价是列序必须手工对齐 SQLite 新库的物理列序（``SELECT d.*`` 无
  response_model，列集会整个泄进 erpAPI 的响应），verify_schema() 负责守住。
* FTS5 虚表 + 3 个触发器 + rebuild 探针 —— 换成 pg_trgm 的 3 个表达式 GIN 索引。
"""
from __future__ import annotations

import logging
from typing import Dict, List

logger = logging.getLogger(__name__)

# 时间戳列的默认值：与 SQLite 的 CURRENT_TIMESTAMP 逐字节同格式（UTC，无小数秒）
TS_DEFAULT = "to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')"

# ASCII-only 折叠函数。**不要**用 lower()/ILIKE：它们折叠全 Unicode，
# 而 SQLite 的 LIKE 与 FTS5 trigram 只折叠 ASCII（实测 'CAFÉ CREME' 不匹配
# '%café%'）。IMMUTABLE + 与 collation 无关，所以能进表达式索引。
ASCII_LOWER_FN = """
CREATE OR REPLACE FUNCTION public.ascii_lower(t text)
RETURNS text
LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT
AS $fn$
  SELECT translate($1, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz')
$fn$;
"""

# ------------------------------------------------------------------
# 建表：顺序 = SQLite 新库的物理列序（CREATE TABLE 的列 + 之后 ALTER 上去的列）
# ------------------------------------------------------------------

DDL_TABLES: List[str] = [
    # ---------------- batches（18 列）----------------
    # 注意 batch_type / discover_mode 在 SQLite 里是 ALTER 加的，所以排在
    # created_at / updated_at **之后**。get_batch_by_name 是 SELECT *，
    # 整张表的列都会泄给调用方。
    f"""
    CREATE TABLE IF NOT EXISTS batches (
        id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name                   text COLLATE "C" NOT NULL UNIQUE,
        needs_screenshot       integer DEFAULT 0,
        is_auto                integer DEFAULT 0,
        expand_variants        integer DEFAULT 0,
        status                 text COLLATE "C" DEFAULT 'running',
        completed_at           text COLLATE "C",
        external_id            text COLLATE "C",
        callback_url           text COLLATE "C",
        callback_status        text COLLATE "C",
        callback_attempts      integer DEFAULT 0,
        callback_next_retry_at text COLLATE "C",
        callback_last_error    text COLLATE "C",
        callback_sent_at       text COLLATE "C",
        created_at             text COLLATE "C" DEFAULT {TS_DEFAULT},
        updated_at             text COLLATE "C" DEFAULT {TS_DEFAULT},
        batch_type             text COLLATE "C" NOT NULL DEFAULT 'asin',
        discover_mode          text COLLATE "C"
    );
    """,

    # ---------------- batch_asins（3 列）----------------
    """
    CREATE TABLE IF NOT EXISTS batch_asins (
        batch_id bigint NOT NULL,
        asin     text COLLATE "C" NOT NULL,
        is_new   integer DEFAULT 0,
        PRIMARY KEY (batch_id, asin)
    );
    """,

    # ---------------- asin_data（55 列）----------------
    # 列集与列序是 API 契约的一部分：变异测试证实"加一列"会产生 21 处基线差异。
    f"""
    CREATE TABLE IF NOT EXISTS asin_data (
        id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        asin                        text COLLATE "C" NOT NULL UNIQUE,
        title                       text COLLATE "C",
        brand                       text COLLATE "C",
        product_type                text COLLATE "C",
        manufacturer                text COLLATE "C",
        model_number                text COLLATE "C",
        part_number                 text COLLATE "C",
        country_of_origin           text COLLATE "C",
        is_customized               text COLLATE "C",
        best_sellers_rank           text COLLATE "C",
        original_price              text COLLATE "C",
        current_price               text COLLATE "C",
        buybox_price                text COLLATE "C",
        buybox_shipping             text COLLATE "C",
        is_fba                      text COLLATE "C",
        stock_count                 text COLLATE "C",
        stock_status                text COLLATE "C",
        delivery_date               text COLLATE "C",
        delivery_time               text COLLATE "C",
        image_urls                  text COLLATE "C",
        bullet_points               text COLLATE "C",
        long_description            text COLLATE "C",
        upc_list                    text COLLATE "C",
        ean_list                    text COLLATE "C",
        parent_asin                 text COLLATE "C",
        variation_asins             text COLLATE "C",
        variant_attributes          text COLLATE "C",
        root_category_id            text COLLATE "C",
        category_ids                text COLLATE "C",
        category_tree               text COLLATE "C",
        first_available_date        text COLLATE "C",
        package_dimensions          text COLLATE "C",
        package_weight              text COLLATE "C",
        item_dimensions             text COLLATE "C",
        item_weight                 text COLLATE "C",
        product_url                 text COLLATE "C",
        site                        text COLLATE "C" DEFAULT 'amazon.com',
        zip_code                    text COLLATE "C" DEFAULT '10001',
        crawl_time                  text COLLATE "C",
        screenshot_path             text COLLATE "C",
        content_hash                text COLLATE "C",
        title_bullets_hash          text COLLATE "C",
        baseline_price              text COLLATE "C",
        baseline_buybox_price       text COLLATE "C",
        baseline_stock_count        text COLLATE "C",
        baseline_stock_status       text COLLATE "C",
        baseline_title_bullets_hash text COLLATE "C",
        baseline_updated_at         text COLLATE "C",
        rating                      text COLLATE "C",
        review_count                text COLLATE "C",
        seller_id                   text COLLATE "C",
        seller_name                 text COLLATE "C",
        created_at                  text COLLATE "C" DEFAULT {TS_DEFAULT},
        updated_at                  text COLLATE "C" DEFAULT {TS_DEFAULT}
    );
    """,

    # ---------------- asin_changes（8 列）----------------
    f"""
    CREATE TABLE IF NOT EXISTS asin_changes (
        id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        asin          text COLLATE "C" NOT NULL,
        batch_id      bigint,
        change_type   text COLLATE "C" NOT NULL,
        change_detail text COLLATE "C",
        prev_value    text COLLATE "C",
        new_value     text COLLATE "C",
        created_at    text COLLATE "C" DEFAULT {TS_DEFAULT}
    );
    """,

    # ---------------- tasks（17 列）----------------
    f"""
    CREATE TABLE IF NOT EXISTS tasks (
        id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        batch_id         bigint NOT NULL,
        asin             text COLLATE "C" NOT NULL,
        zip_code         text COLLATE "C" DEFAULT '10001',
        status           text COLLATE "C" DEFAULT 'pending',
        priority         integer DEFAULT 0,
        needs_screenshot integer DEFAULT 0,
        worker_id        text COLLATE "C",
        lease_epoch      integer DEFAULT 0,
        retry_count      integer DEFAULT 0,
        auto_retry_count integer DEFAULT 0,
        error_type       text COLLATE "C",
        error_detail     text COLLATE "C",
        created_at       text COLLATE "C" DEFAULT {TS_DEFAULT},
        updated_at       text COLLATE "C" DEFAULT {TS_DEFAULT},
        task_type        text COLLATE "C" NOT NULL DEFAULT 'asin',
        task_meta        text COLLATE "C",
        UNIQUE (batch_id, asin)
    );
    """,

    # ---------------- screenshots（9 列）----------------
    f"""
    CREATE TABLE IF NOT EXISTS screenshots (
        id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        asin         text COLLATE "C" NOT NULL,
        batch_id     bigint NOT NULL,
        status       text COLLATE "C" DEFAULT 'pending',
        retry_count  integer DEFAULT 0,
        error_detail text COLLATE "C",
        file_path    text COLLATE "C",
        created_at   text COLLATE "C" DEFAULT {TS_DEFAULT},
        updated_at   text COLLATE "C" DEFAULT {TS_DEFAULT},
        UNIQUE (batch_id, asin)
    );
    """,

    # ---------------- seller_discoveries（7 列）----------------
    f"""
    CREATE TABLE IF NOT EXISTS seller_discoveries (
        batch_id      bigint NOT NULL,
        seller_id     text COLLATE "C" NOT NULL,
        asin          text COLLATE "C" NOT NULL,
        list_title    text COLLATE "C",
        list_price    text COLLATE "C",
        list_image    text COLLATE "C",
        discovered_at text COLLATE "C" DEFAULT {TS_DEFAULT},
        PRIMARY KEY (batch_id, seller_id, asin)
    );
    """,
]

# ------------------------------------------------------------------
# 索引：与 common/database.py:440-607 + 711-717 一一对应
# ------------------------------------------------------------------

DDL_INDEXES: List[str] = [
    "CREATE INDEX IF NOT EXISTS idx_batch_asins_asin ON batch_asins(asin)",

    "CREATE INDEX IF NOT EXISTS idx_changes_asin ON asin_changes(asin)",
    "CREATE INDEX IF NOT EXISTS idx_changes_type ON asin_changes(change_type)",
    "CREATE INDEX IF NOT EXISTS idx_changes_batch_type ON asin_changes(batch_id, change_type)",

    "CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status)",
    "CREATE INDEX IF NOT EXISTS idx_tasks_batch ON tasks(batch_id)",
    "CREATE INDEX IF NOT EXISTS idx_tasks_status_priority ON tasks(status, priority DESC)",
    "CREATE INDEX IF NOT EXISTS idx_tasks_status_worker ON tasks(status, worker_id, updated_at)",
    "CREATE INDEX IF NOT EXISTS idx_tasks_status_updated ON tasks(status, updated_at)",
    # 覆盖索引：让 get_batches 的分组统计走 index-only
    "CREATE INDEX IF NOT EXISTS idx_tasks_batch_status ON tasks(batch_id, status)",

    "CREATE INDEX IF NOT EXISTS idx_screenshots_status ON screenshots(status)",
    "CREATE INDEX IF NOT EXISTS idx_screenshots_batch ON screenshots(batch_id)",

    "CREATE INDEX IF NOT EXISTS idx_seller_disc_seller ON seller_discoveries(seller_id)",
    "CREATE INDEX IF NOT EXISTS idx_seller_disc_asin ON seller_discoveries(asin)",
    "CREATE INDEX IF NOT EXISTS idx_seller_disc_batch ON seller_discoveries(batch_id)",

    "CREATE INDEX IF NOT EXISTS idx_batches_callback_pending "
    "ON batches(callback_status, callback_next_retry_at)",
]

# pg_trgm：替代 FTS5 虚表。表达式索引必须与查询里的表达式**逐字一致**，
# 否则用不上（results_read.py 必须写 ``ascii_lower(d.title) LIKE ascii_lower(?)``，
# 或者用 ``col LIKE ?`` 让 pool.translate_sql 自动改写成同一形状）。
# 实测 200k 行：建索引 6.4s，三个索引合计约 29MB（FTS5 同规模约 90MB）。
DDL_TRGM_INDEXES: List[str] = [
    "CREATE INDEX IF NOT EXISTS idx_asin_data_asin_trgm "
    "ON asin_data USING gin (public.ascii_lower(asin) public.gin_trgm_ops)",
    "CREATE INDEX IF NOT EXISTS idx_asin_data_title_trgm "
    "ON asin_data USING gin (public.ascii_lower(title) public.gin_trgm_ops)",
    "CREATE INDEX IF NOT EXISTS idx_asin_data_brand_trgm "
    "ON asin_data USING gin (public.ascii_lower(brand) public.gin_trgm_ops)",
]

# 一次性 backfill，逐字移植自 common/database.py:722-743。
# 新库上匹配 0 行（等于 no-op），但升级路径要靠它。
# 语法完全可移植；tasks.batch_id / screenshots.batch_id 都是 NOT NULL，
# 所以 ``id NOT IN (subquery)`` 不会撞上 NULL 全空的坑。
BACKFILL_LEGACY_BATCHES = """
UPDATE batches
   SET status='completed',
       completed_at=COALESCE(updated_at, created_at),
       callback_status='disabled'
 WHERE COALESCE(status,'running')='running'
   AND callback_status IS NULL
   AND id NOT IN (
     SELECT DISTINCT batch_id FROM tasks
      WHERE status NOT IN ('done','failed')
   )
   AND id NOT IN (
     SELECT DISTINCT batch_id FROM screenshots
      WHERE status NOT IN ('done','failed')
   )
"""

# ------------------------------------------------------------------
# 期望列序：verify_schema() 用它做硬闸门。
# 来自 SQLite 新库（CREATE TABLE 的列 + ALTER 追加的列）的实际物理顺序。
# ``SELECT *`` / ``SELECT d.*`` 没有 response_model 过滤，改这里 = 改 API。
# ------------------------------------------------------------------
EXPECTED_COLUMNS: Dict[str, List[str]] = {
    "batches": [
        "id", "name", "needs_screenshot", "is_auto", "expand_variants", "status",
        "completed_at", "external_id", "callback_url", "callback_status",
        "callback_attempts", "callback_next_retry_at", "callback_last_error",
        "callback_sent_at", "created_at", "updated_at", "batch_type", "discover_mode",
    ],
    "batch_asins": ["batch_id", "asin", "is_new"],
    "asin_data": [
        "id", "asin", "title", "brand", "product_type", "manufacturer",
        "model_number", "part_number", "country_of_origin", "is_customized",
        "best_sellers_rank", "original_price", "current_price", "buybox_price",
        "buybox_shipping", "is_fba", "stock_count", "stock_status", "delivery_date",
        "delivery_time", "image_urls", "bullet_points", "long_description",
        "upc_list", "ean_list", "parent_asin", "variation_asins",
        "variant_attributes", "root_category_id", "category_ids", "category_tree",
        "first_available_date", "package_dimensions", "package_weight",
        "item_dimensions", "item_weight", "product_url", "site", "zip_code",
        "crawl_time", "screenshot_path", "content_hash", "title_bullets_hash",
        "baseline_price", "baseline_buybox_price", "baseline_stock_count",
        "baseline_stock_status", "baseline_title_bullets_hash",
        "baseline_updated_at", "rating", "review_count", "seller_id", "seller_name",
        "created_at", "updated_at",
    ],
    "asin_changes": [
        "id", "asin", "batch_id", "change_type", "change_detail",
        "prev_value", "new_value", "created_at",
    ],
    "tasks": [
        "id", "batch_id", "asin", "zip_code", "status", "priority",
        "needs_screenshot", "worker_id", "lease_epoch", "retry_count",
        "auto_retry_count", "error_type", "error_detail", "created_at",
        "updated_at", "task_type", "task_meta",
    ],
    "screenshots": [
        "id", "asin", "batch_id", "status", "retry_count", "error_detail",
        "file_path", "created_at", "updated_at",
    ],
    "seller_discoveries": [
        "batch_id", "seller_id", "asin", "list_title", "list_price",
        "list_image", "discovered_at",
    ],
}

# 带 identity 序列的表（DELETE /api/database 要把它们重启回 1）
IDENTITY_TABLES = ["batches", "asin_data", "asin_changes", "tasks", "screenshots"]

# SQLite 版 `DELETE /api/database` 清空的 6 张表。
# ⚠ 不含 seller_discoveries —— SQLite 版就不删它，保持等价。
CLEARED_TABLES = ["asin_changes", "asin_data", "batch_asins",
                  "tasks", "screenshots", "batches"]


class SchemaMixin:
    """DDL。只依赖 PoolMixin 提供的 ``self._db`` / ``self._pool``。"""

    async def init_tables(self):
        """建表建索引。幂等：可以对着已有库反复跑。

        每条语句独立自动提交（不裹在一个事务里）——这是刻意的：
        SQLite 版靠 isolation_level=None 让每条 DDL 单独提交，PG 里若裹成一个
        事务，任何一条失败都会让后面全部 ``InFailedSQLTransactionError``。
        """
        conn = self._write_conn
        if conn is None:
            raise RuntimeError("init_tables 需要已建立的写连接")

        # pg_trgm + ascii_lower：需要建扩展的权限。生产角色若没有，
        # 把这两步挪到独立的 bootstrap 脚本，init_tables 只管假设它已就绪。
        try:
            await conn.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
        except Exception as e:  # noqa: BLE001
            logger.warning("pg_trgm 扩展创建失败（搜索会退化成顺序扫描）: %s", e)
        await conn.execute(ASCII_LOWER_FN)

        for stmt in DDL_TABLES:
            await conn.execute(stmt)
        for stmt in DDL_INDEXES:
            await conn.execute(stmt)
        for stmt in DDL_TRGM_INDEXES:
            try:
                await conn.execute(stmt)
            except Exception as e:  # noqa: BLE001
                # 与 SQLite 版一致：搜索索引建不出来只告警，不挡启动
                logger.warning("trgm 索引初始化异常（不影响核心功能）: %s", e)

        try:
            tag = await conn.execute(BACKFILL_LEGACY_BATCHES)
            n = int(str(tag).rsplit(" ", 1)[-1])
            if n > 0:
                logger.info("数据库迁移: 回填 %d 个老批次为 completed", n)
        except Exception as e:  # noqa: BLE001
            logger.warning("老批次 backfill 异常: %s", e)

    async def verify_schema(self, strict: bool = True) -> List[str]:
        """比对实际列序与 EXPECTED_COLUMNS。返回问题列表（空 = 一致）。

        存在的理由：``SELECT d.*`` 没有 response_model，任何多出来/少掉/换位的列
        都会直接改变 erpAPI 看到的响应。把"永远别给 asin_data 加列"从注释
        升级成硬闸门。
        """
        conn = self._write_conn
        problems: List[str] = []
        for table, expected in EXPECTED_COLUMNS.items():
            rows = await conn.fetch(
                "SELECT column_name FROM information_schema.columns "
                "WHERE table_schema='public' AND table_name=$1 "
                "ORDER BY ordinal_position", table)
            actual = [r["column_name"] for r in rows]
            if actual != expected:
                problems.append(
                    f"{table}: 列序/列集不符\n  期望={expected}\n  实际={actual}")
        if problems and strict:
            raise RuntimeError("PG schema 与 SQLite 基线不一致:\n" + "\n".join(problems))
        return problems

    async def reset_all(self):
        """清空全部业务表并把 identity 重置回 1（测试夹具用）。

        与 `DELETE /api/database` 的语义一致：不动 seller_discoveries 之外的
        取舍见 CLEARED_TABLES 注释。这里为了测试可重复性把它也一并清掉。
        """
        conn = self._write_conn
        await conn.execute(
            "TRUNCATE asin_changes, asin_data, batch_asins, tasks, "
            "screenshots, batches, seller_discoveries RESTART IDENTITY")
